apiVersion: v1
kind: Service
metadata:
  name: invest-inference
  namespace: mlops
  labels:
    app: invest-inference
spec:
  type: ClusterIP
  selector:
    app: invest-inference
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
